### ISSUE TITLE
Cleaning fails with PG::UndefinedColumn: ERROR: column "increment_by" does not exist

### ISSUE THREAD

**Issue by jamesbebbington** [DatabaseCleaner/database_cleaner-active_record#72]
I'm in the process of upgrading a rails app from Rails 3.2 LTS to Rails 4.0. Under Rails 3.2 database_cleaner was operating fine, but under 4.0, some feature specs are failing with errors of the form:

```
ActiveRecord::StatementInvalid:
PG::UndefinedColumn: ERROR:  column "increment_by" does not exist
LINE 1: ...foos_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_...
 : SELECT setval('"foos_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_by FROM "foos_id_seq"), (SELECT min_value FROM "foos_id_seq")) FROM "foos"), false)
```

I've recreated the `test` db and tried both the `:deletion` and `:truncation` strategies along with all their various options, but to no avail. Can anyone shed any light on why it might be breaking?

ruby: `2.3.8`
rails: `4.0.13`
database_cleaner: `1.99.0`
PostgreSQL: `13.4`

**Comment by edouard** [comment]
Rails 4.2 is not compatible with Postgres >= 10. A fix was made for rails 5 but hasn’t been backported to the 4 series since it’s EOL.

[This monkey patch ](https://github.com/rails/rails/issues/28780#issuecomment-354868174) for rails 4.2 addresses the issue, but it would have to be back ported to rails 4.0 or 4.1.

**Comment by jamesbebbington** [comment]
Thanks @edouard!
